### ISSUE TITLE
add kowl ui

### ISSUE THREAD

**Issue by tzookb** [tzookb/learn-kafka#3]
```
kowl-ui:
    image: quay.io/cloudhut/kowl:latest
    hostname: kowl
    container_name: kowl
    depends_on:
      schema-registry:
        condition: service_healthy
    ports:
      - "8000:8080"
    environment:
      KAFKA_BROKERS: 'broker:29092'
      KAFKA_SCHEMAREGISTRY_ENABLED: 'true'
      KAFKA_SCHEMAREGISTRY_URLS: "http://schema-registry:8081"
      CONNECT_ENABLED: 'true'
      CONNECT_CLUSTERS_NAME: 'debezium'
      CONNECT_CLUSTERS_URL: "http://debezium-connector:8083"
```
